- name: Prepare build server
  hosts: build

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - git
        - maven
        - docker.io
      state: present

- name: Prepare staging server
  hosts: staging

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - docker.io
      state: present