- name: Wait till reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

- name: Prepare build server
  hosts: build

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - git
        - maven
        - docker.io
      state: present

- name: Prepare staging server
  hosts: staging

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - docker.io
      state: present