- name: Prepare build server
  hosts: build

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - git
        - maven
        - docker.io
      state: present

  - name: Copy Docker secret to build server
    copy:
      src: dockersecret
      dest: /root/

- name: Prepare staging server
  hosts: staging

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - tomcat9
        - docker.io
      state: present